<#
.SYNOPSIS
    check-plugin-integrity.ps1, part 3 of 4: the entry format (check 13), the branch templates held
    against the scaffolder (13b), the [COVERAGE] contract every category closes with, and the
    staleness checks on claimed shapes and measured figures.

.DESCRIPTION
    The fixture, the assert helpers and Invoke-Integrity live in check-plugin-integrity-fixture.ps1,
    which also records why this suite is four files.

    Several scenarios here pass -Full to Invoke-Integrity, and that is load-bearing: the two
    branch-template scenarios and the [COVERAGE] scenario assert about the three checks the fixture
    skips for speed. An ABSENCE assert under a skip would pass vacuously, which is why the skip list
    is documented beside Invoke-Integrity rather than here.

    Pure ASCII (repo convention for .ps1).
#>
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'check-plugin-integrity-fixture.ps1')

$Fixture = Join-Path ([System.IO.Path]::GetTempPath()) ("check-plugin-integrity-entries-$PID-$([guid]::NewGuid().ToString('n'))")

try {
    New-IntegrityFixture -Fixture $Fixture

    # --- Scenario 34: check 13, entry heading levels (this repo's own defect, four times in one day) ---
    #     An entry body used a sub-heading at the entry's own level, so the two became siblings: after the
    #     fold CHANGELOG.md carried headings with no PR number, and the release renderer split an entry on
    #     every one of them, shipping "entries" with no number, no type and no Plugins line. Rendall's lens
    #     warned about it and the warning did not stop it, which is the whole argument for a gate: the rule
    #     is exactly checkable.
    #
    #     REWRITTEN FOR THE FLAT CHANGELOG (August 5, 2026). An entry became an H2 with three named H3
    #     sections, so the forbidden levels moved up by one AND a second, new rule joined them: a heading
    #     AT the section level that is not one of the declared sections. Both halves are asserted here,
    #     and so is the case that must stay silent -- the real section headings, which the pre-flat
    #     version of this check would have reported as a defect each.
    #
    #     AND SHIFTED ONE LEVEL DEEPER AGAIN (August 26, 2026), when '## [Unreleased]' took H2 and both level
    #     pairs moved down. The levels below are COMPOSED from the lib rather than typed, which is the whole
    #     lesson of that shift for this file: a fixture that states the format in literals is a second
    #     definition of it, and the check under test reads the first one. Typed out, these headings went on
    #     describing yesterday's document while the gate judged today's.
    $s34Md = [char]0x00B7
    $s34EntryH = '#' * (Get-EntryHeadingLevel)
    $s34SectH  = '#' * (Get-EntrySectionLevel)
    $s34SubH   = '#' * ((Get-EntrySectionLevel) + 1)
    $s34Sections = @(
        "$s34SectH What does this change do?"
        ''
        'A body with a correctly demoted sub-heading.'
        ''
        "$s34SubH Tested"
        ''
        'All green.'
        ''
        "$s34SectH Significance"
        ''
        "$s34SubH Tier 0"
        ''
        'Only this repo notices.'
        ''
        'Score: 2'
        ''
        "$s34SectH Type of change"
        ''
        'Fix'
    )
    # --- check 13b: no branch document is left behind between branches ----------------------------
    # WHAT THIS PINS HAS BEEN INVERTED, AND THE ARGUMENT BEHIND IT DID NOT SURVIVE INTACT (August 23, 2026).
    # It held two generated templates under branch/templates/ to Get-BranchTemplates, then the merged
    # document's RESET state to the formatter, both on the same reasoning: a document generated by a
    # formatter must not become a second definition of the format. That reasoning needed a generated
    # document to hold, and there is none -- the document exists for the lifetime of a branch, so the trunk
    # carries no copy and a hand-edit to a reset state is not a thing that can happen.
    #
    # SO THE SUBJECT IS THE INVARIANT THAT REPLACED IT: no document anywhere declares the trunk. Absent is
    # the trunk's normal state, a document naming this branch is work in progress, and one naming the trunk
    # is a leftover from a fold that ran under the older behaviour. Asserted in every direction, because a
    # check that only ever passes is indistinguishable from one that reads nothing.
    Write-Host 'check 13b -- no branch document is left behind between branches' -ForegroundColor Cyan
    $bdRel  = (Get-BranchFilePaths).File -replace '/', '\'
    $bdPath = Join-Path $Fixture $bdRel
    New-Item -ItemType Directory -Path (Split-Path -Parent $bdPath) -Force | Out-Null
    if (Test-Path -LiteralPath $bdPath) { Remove-Item -LiteralPath $bdPath -Force }

    $r13bAbsent = Invoke-Integrity -FixtureRoot $Fixture -Full
    Assert-True (-not ($r13bAbsent.Out -match '\[branch-template\].*names the trunk')) 'check 13b: an absent document is the trunk in its normal state, and is silent'
    Assert-True ($r13bAbsent.Out -match '\[branch-template\] checked 1') 'check 13b: and it was actually examined -- the pass is not an empty scan'
    Assert-True ($r13bAbsent.Out -match 'absent, which is the trunk between branches') 'check 13b: the coverage line says WHICH state it found, so a pass cannot read as a skip'

    # A DOCUMENT HOLDING A BRANCH'S WORK IS FINE, which is the ordinary state on any branch -- including the
    # branch this check is running on.
    [System.IO.File]::WriteAllText($bdPath, (((Format-Development -Branch 'feat/somebodys-work-v1' -Id '20260823-090000') -join "`n") + "`n"), $Utf8NoBom)
    $r13bOnBranch = Invoke-Integrity -FixtureRoot $Fixture -Full
    Assert-True (-not ($r13bOnBranch.Out -match '\[branch-template\].*names the trunk')) 'check 13b: a document holding a branch''s work is not a finding'
    Assert-True ($r13bOnBranch.Out -match "declaring 'feat/somebodys-work-v1'") 'check 13b: and the coverage line names whose work it is'

    # THE LEFTOVER. This is the exact file the old behaviour wrote on every fold, so this case is what the
    # inversion is FOR: what used to be the asserted-correct state is now the one error.
    [System.IO.File]::WriteAllText($bdPath, (((Format-Development -Branch '') -join "`n") + "`n"), $Utf8NoBom)
    $r13bLeftover = Invoke-Integrity -FixtureRoot $Fixture -Full
    Assert-Equal 1 $r13bLeftover.Code 'check 13b: a document declaring the trunk is an error'
    Assert-True ($r13bLeftover.Out -match 'names the trunk') 'check 13b: and the message says what is wrong with it'
    Assert-True ($r13bLeftover.Out -match 'Delete it') 'check 13b: and what to do about it, since the repair is one command'

    # A DOCUMENT BELONGING TO NOBODY. Every reader of this file -- the fold, the two local gates, the CI gate
    # -- identifies a branch's work by the name in the heading, so one without a name is unreadable to all of
    # them. Reported rather than passed, because silence here is what a hand-created file would buy.
    [System.IO.File]::WriteAllText($bdPath, "# Development`n`nNo branch named anywhere.`n", $Utf8NoBom)
    $r13bNameless = Invoke-Integrity -FixtureRoot $Fixture -Full
    Assert-Equal 1 $r13bNameless.Code 'check 13b: a document declaring no branch at all is an error'
    Assert-True ($r13bNameless.Out -match 'declares no branch in its heading') 'check 13b: and it is reported as its own case, not as a trunk leftover'

    # THE CHECK READS THE FIXTURE'S OWN repo-config, and it still has to now that it generates no content.
    # Get-BranchTrunkName is a seam: a repo whose trunk is 'master' has a DIFFERENT set of documents that
    # count as leftovers, and answering it from this repo's default would pass exactly the file that repo
    # needs caught. Asserted in both directions on one fixture, because silence alone is also what a check
    # that stopped reading would produce.
    $fixCfgDir = Join-Path $Fixture 'scripts'
    New-Item -ItemType Directory -Path $fixCfgDir -Force | Out-Null
    $fixCfg = Join-Path $fixCfgDir 'repo-config.ps1'
    [System.IO.File]::WriteAllText($fixCfg, "function Get-TrunkBranchName { 'master' }`n", $Utf8NoBom)
    $masterReset = & {
        . $fixCfg
        . (Join-Path $PSScriptRoot '..\lib\entry-scaffold-lib.ps1')
        ((Format-Development -Branch '') -join "`n") + "`n"
    }
    [System.IO.File]::WriteAllText($bdPath, $masterReset, $Utf8NoBom)
    $r13bMaster = Invoke-Integrity -FixtureRoot $Fixture -Full
    Assert-Equal 1 $r13bMaster.Code 'check 13b: a leftover naming the FIXTURE''s trunk is caught, not this repo''s'
    Assert-True ($r13bMaster.Out -match "names the trunk \('master'\)") 'check 13b: and the message quotes the trunk that fixture actually declared'

    # The mirror image on the same fixture: 'main' is an ordinary branch name in a repo whose trunk is
    # 'master', so the very shape that was an error two asserts ago must now be silent.
    [System.IO.File]::WriteAllText($bdPath, (((Format-Development -Branch 'main' -Id '20260823-090000') -join "`n") + "`n"), $Utf8NoBom)
    $r13bMainOnMaster = Invoke-Integrity -FixtureRoot $Fixture -Full
    Assert-True (-not ($r13bMainOnMaster.Out -match '\[branch-template\].*names the trunk')) `
        'check 13b: and where the trunk is master, a document naming main is just a branch'
    # Back to the absent state with no config, so nothing after this inherits the fixture's answer.
    Remove-Item -LiteralPath $fixCfg -Force
    Remove-Item -LiteralPath $bdPath -Force

    Write-Host 'check 13 -- an entry is an H3 with two named H4 sections, and a body heading may be neither' -ForegroundColor Cyan
    $s34Entry = Join-Path $Fixture 'fix-a-branch-name.md'
    $s34Good = @("$s34EntryH A fixture entry") + @('') + $s34Sections
    [System.IO.File]::WriteAllText($s34Entry, (($s34Good -join "`n") + "`n"), $Utf8NoBom)
    $r34a = Invoke-Integrity -FixtureRoot $Fixture
    # THE ASSERT THAT MATTERS MOST HERE, because the whole entry format would trip a level-only rule: the
    # declared section headings sit at the section level BY DESIGN and must be silent, while a sub-heading
    # one level deeper inside one of them is the ordinary accepted case.
    Assert-True (-not ($r34a.Out -match 'entry-heading.*fix-a-branch-name')) 'scenario 34: the declared sections plus a deeper sub-heading are accepted'
    Assert-True ($r34a.Out -match '\[entry-heading\] checked') 'scenario 34: and the entry file WAS examined -- the pass is not an empty scan'
    Assert-True ($r34a.Out -match '\[entry-heading\].*1 unfolded entry\(ies\)') 'scenario 34: an entry file at the current level is RECOGNISED as one -- the detector was pinned one level off until August 5, 2026, so this check silently judged nothing'

    # Defect one: a heading at the entry's own level inside the body. This is the old "$s34SectH Tested" defect,
    # one level up, and now the worse one -- it becomes a separate entry rather than a stray sub-heading.
    $s34Bad = @($s34Good) -replace ("^" + $s34SubH + " Tested$"), "$s34EntryH Tested"
    [System.IO.File]::WriteAllText($s34Entry, (($s34Bad -join "`n") + "`n"), $Utf8NoBom)
    $r34b = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($r34b.Out -match 'entry-heading.*fix-a-branch-name\.md:7') 'scenario 34: a heading at the entry level in a body is reported, with its line number'
    Assert-True ($r34b.Out -match 'SEPARATE entry') 'scenario 34: and the message says WHY, by naming the consequence at fold time'
    Assert-True ($r34b.Out -match 'undeclared tier 0') 'scenario 34: including what the phantom entry declares -- nothing'

    # Defect two, new with the format: a heading at the SECTION level that is not a declared section. The
    # dangerous version of this is a MISSPELLED section heading, which costs the entry its declaration
    # silently -- so the fixture uses exactly that rather than an obviously unrelated word.
    $s34Typo = @($s34Good) -replace ('^' + $s34SectH + ' Significance$'), "$s34SectH Significanse"
    [System.IO.File]::WriteAllText($s34Entry, (($s34Typo -join "`n") + "`n"), $Utf8NoBom)
    $r34c = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($r34c.Out -match 'entry-heading.*fix-a-branch-name\.md:11') 'scenario 34: a misspelled section heading is reported, with its line'
    Assert-True ($r34c.Out -match 'not one of them') 'scenario 34: and the message lists the sections that ARE declared'
    Assert-True ($r34c.Out -match 'loses that declaration') 'scenario 34: naming the silent cost rather than only the rule'

    # Defect three (issue #1367): a DECLARED section heading that appears TWICE in one entry. Both copies
    # are valid names, so the misspelling rule above says nothing -- the entry validates and every gate
    # passes, and the split only shows in a published Release body, because the fold links the LAST copy
    # while the release renderer reads the FIRST. The fixture doubles 'Significance', which is exactly the
    # shape the v4.29.0 body shipped ('#### Pull Request' twice, the linkless copy chosen).
    $s34DupSection = @($s34Good) + @('', "$s34SectH Significance", '', 'A stray second copy.')
    [System.IO.File]::WriteAllText($s34Entry, (($s34DupSection -join "`n") + "`n"), $Utf8NoBom)
    $r34c2 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($r34c2.Out -match 'entry-heading.*fix-a-branch-name\.md:23') 'scenario 34: a repeated declared section is reported, on the SECOND occurrence''s line'
    Assert-True ($r34c2.Out -match "a second 'Significance' section") 'scenario 34: and the message names which section was doubled'
    Assert-True ($r34c2.Out -match 'no PR link') 'scenario 34: naming the silent published cost, and #1367'

    # The negative that keeps this from over-firing: a repeated heading QUOTED in a fence is a mention,
    # not a use -- and this branch's own changelog entry does exactly that.
    $s34DupFenced = @(
        "$s34EntryH A fixture entry"
        ''
        "$s34SectH What does this change do?"
        ''
        'The doubled form looks like this:'
        ''
        '```markdown'
        "$s34SectH Significance"
        "$s34SectH Significance"
        '```'
        ''
        "$s34SectH Significance"
        ''
        'Score: 2'
        ''
        "$s34SectH Type of change"
        ''
        'Fix'
    )
    [System.IO.File]::WriteAllText($s34Entry, (($s34DupFenced -join "`n") + "`n"), $Utf8NoBom)
    $r34c3 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($r34c3.Out -match 'entry-heading.*fix-a-branch-name')) 'scenario 34: a duplicated section heading inside a fence is a mention, not a finding'

    # Fence-aware: an entry that QUOTES a heading is discussing structure, not creating it -- the
    # mention-versus-use question this file answers in four other checks, and one this repo's own entry
    # files do (the entry for this very change quotes the format).
    $s34Fenced = @(
        "$s34EntryH A fixture entry"
        ''
        "$s34SectH What does this change do?"
        ''
        'The wrong form looks like this:'
        ''
        '```markdown'
        "$s34EntryH Tested"
        "$s34SectH Significanse"
        '```'
        ''
        "$s34SectH Significance"
        ''
        "$s34SubH Tier 0"
        ''
        'Only this repo notices.'
        ''
        'Score: 2'
        ''
        "$s34SectH Type of change"
        ''
        'Fix'
    )
    [System.IO.File]::WriteAllText($s34Entry, (($s34Fenced -join "`n") + "`n"), $Utf8NoBom)
    $r34d = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($r34d.Out -match 'entry-heading.*fix-a-branch-name')) 'scenario 34: both fenced examples are mentions, not uses -- neither level is reported'

    # A PRE-FORMAT entry file, which is not history: an entry file lives only on a branch, so a branch
    # opened in the flat window (August 5-26, 2026) still carries the shape from then -- the entry one level
    # below the current heading -- and this repo had one parked on the remote the day the format landed. It
    # must still be RECOGNISED (line 1 is skipped whatever its level, because the fold re-levels it) while
    # its body is judged by the same rules. The heading is composed as 'entryLevel - 1' rather than typed:
    # the detector ranges DOWN from the current level since issue #1344, and a literal would pin yesterday's.
    $s34Legacy = @(
        ('#' * ((Get-EntryHeadingLevel) - 1)) + " An older entry " + $s34Md + ' Fix ' + $s34Md + ' 2026-08-01'
        ''
        'Body prose.'
        ''
        "$s34EntryH Not allowed here either"
    )
    [System.IO.File]::WriteAllText($s34Entry, (($s34Legacy -join "`n") + "`n"), $Utf8NoBom)
    $r34e = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($r34e.Out -match '\[entry-heading\].*1 unfolded entry\(ies\)') 'scenario 34: a pre-format flat-window entry file is still recognised as an entry file'
    Assert-True ($r34e.Out -match 'entry-heading.*fix-a-branch-name\.md:5') 'scenario 34: and its body is judged by the same rules'
    Assert-True (-not ($r34e.Out -match 'fix-a-branch-name\.md:1')) 'scenario 34: while its own heading on line 1 is NOT reported -- that is the entry, and the fold re-levels it'
    Remove-Item -LiteralPath $s34Entry -Force

    # The CHANGELOG half, which is what cut-release actually parses -- and the half that catches damage
    # arriving through the fold, the one write that happens directly on main past every PR gate.
    $s34Cl = Join-Path $Fixture 'dkj-policy\CHANGELOG.md'
    $s34ClGood = @(
        '# Changelog'
        ''
        'Everything merged since the last release, furthest reach first.'
        ''
        "$s34EntryH #123 " + $s34Md + ' A real entry'
        ''
    ) + $s34Sections + @('')
    [System.IO.File]::WriteAllText($s34Cl, (($s34ClGood -join "`n") + "`n"), $Utf8NoBom)
    $r34f = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($r34f.Out -match 'entry-heading. CHANGELOG')) 'scenario 34: a well-formed flat changelog is silent'

    # AND SO IS A STAMPED 'Pull Request' HEADING, which is what the fold actually writes into this file
    # (August 19, 2026). This gate compares the whole captured heading text against the declared names, so
    # while it was anchored on a bare '\s*$' the stamp made a declared section unrecognisable -- and the
    # error would have landed HERE, on the one write that happens directly on main past every PR gate,
    # inside the required CI check. Every PR after the first fold would have been blocked by the fold of
    # the one before it. The scenario is the fold's own output rather than a hand-built line, because that
    # is the shape nobody would have thought to type.
    $s34ClStamped = @($s34ClGood) + @(
        "$s34SectH Pull Request " + $s34Md + ' 20260819-171500'
        ''
        '[PR #123](https://gh.test/pr/123)'
        ''
    )
    [System.IO.File]::WriteAllText($s34Cl, (($s34ClStamped -join "`n") + "`n"), $Utf8NoBom)
    $r34f2 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($r34f2.Out -match 'entry-heading. CHANGELOG')) 'scenario 34: a folded entry whose Pull Request heading carries the landing stamp is accepted'
    Assert-True ($r34f2.Out -match '\[entry-heading\] checked') 'scenario 34: and the file WAS examined -- the pass is not an empty scan'

    # THE TOLERANCE IS THE STAMP, NOT THE NAME. A misspelling still has to be caught: this is the failure
    # the exact comparison exists for, and a tail that swallowed anything after the name would have traded
    # one silent defect for another.
    $s34ClMisspelled = @($s34ClStamped) -replace ("^" + $s34SectH + " Pull Request "), "$s34SectH Pull request "
    [System.IO.File]::WriteAllText($s34Cl, (($s34ClMisspelled -join "`n") + "`n"), $Utf8NoBom)
    $r34f3 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($r34f3.Out -match 'entry-heading. CHANGELOG') 'scenario 34: a MISSPELLED section heading is still reported, stamp or no stamp'
    Assert-True ($r34f3.Out -match "'Pull request'") 'scenario 34: and the message quotes the name without the stamp, which is the part to correct'

    [System.IO.File]::WriteAllText($s34Cl, (($s34ClGood -join "`n") + "`n"), $Utf8NoBom)

    # A body sub-heading written at the entry's own level, in the middle of a formatted entry. It SPLITS the
    # entry: the three sections land across two blocks, so the phantom's first section is whichever one
    # followed it -- never the first. That is the rule, and it is structural rather than a guess about intent.
    $s34ClStray = @($s34ClGood) -replace ("^" + $s34SubH + " Tested$"), "$s34EntryH Tested"
    [System.IO.File]::WriteAllText($s34Cl, (($s34ClStray -join "`n") + "`n"), $Utf8NoBom)
    $r34g = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($r34g.Out -match 'entry-heading. CHANGELOG\.md:11') 'scenario 34: a body heading at the entry level is reported, with its line'
    Assert-True ($r34g.Out -match 'has been SPLIT') 'scenario 34: and the message names what happened to the entry rather than only the rule'
    Assert-True ($r34g.Out -match "first named section is 'Significance'") 'scenario 34: quoting the section it starts at, which is the evidence'

    # A DECLARED SECTION REPEATED WITHIN ONE ENTRY, arriving through the fold (issue #1367). This is the
    # half that catches a doubled section on the one write that lands directly on main, past every PR
    # gate -- the v4.29.0 case, where '#### Pull Request' folded in twice and the Release body took the
    # linkless copy. The fixture doubles 'Significance'.
    $s34ClDup = @($s34ClGood) + @("$s34SectH Significance", '', 'A stray second copy of a section.')
    [System.IO.File]::WriteAllText($s34Cl, (($s34ClDup -join "`n") + "`n"), $Utf8NoBom)
    $r34g2 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($r34g2.Out -match 'entry-heading. CHANGELOG\.md:27') 'scenario 34: a repeated declared section in a folded entry is reported, on the second occurrence'
    Assert-True ($r34g2.Out -match "a second 'Significance' section in this H") 'scenario 34: and the message names the doubled section and #1367'

    # THE NEGATIVE THAT SCOPES IT: the SAME section name in two DIFFERENT entries is the norm, not a
    # duplicate -- the check resets per entry. Two well-formed entries, each with its own three sections.
    $s34ClTwo = @(
        '# Changelog'
        ''
        'Everything merged since the last release, furthest reach first.'
        ''
        "$s34EntryH #123 " + $s34Md + ' First entry'
        ''
    ) + $s34Sections + @('') + @(
        "$s34EntryH #124 " + $s34Md + ' Second entry'
        ''
    ) + $s34Sections + @('')
    [System.IO.File]::WriteAllText($s34Cl, (($s34ClTwo -join "`n") + "`n"), $Utf8NoBom)
    $r34g3 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($r34g3.Out -match 'entry-heading. CHANGELOG')) 'scenario 34: one section name per entry across two entries is not a duplicate -- the scan is per entry'

    [System.IO.File]::WriteAllText($s34Cl, (($s34ClGood -join "`n") + "`n"), $Utf8NoBom)

    # THE FALSE POSITIVE THIS AVOIDS, and it is the reason the rule is not simply "an entry heading needs a
    # #NN": the fold cannot reach gh on a manual merge, and then it writes a legitimate entry with no number
    # and no PR footer, saying so on the console. Keying on the number would report the fold's own
    # documented output as a defect.
    #
    # THE LEVEL IS COMPOSED HERE TOO, and it was a typed '^## ' until this line was swept: after the
    # August 26, 2026 shift the pattern matched nothing, so this scenario re-tested the untouched good
    # fixture and passed by asserting the assert two blocks up. The same lesson the block at the top of
    # this scenario draws, in the one place it was not applied.
    $s34ClNoPr = @($s34ClGood) -replace ('^' + $s34EntryH + ' #123 ' + [regex]::Escape($s34Md) + ' A real entry$'), "$s34EntryH A real entry with no PR number"
    [System.IO.File]::WriteAllText($s34Cl, (($s34ClNoPr -join "`n") + "`n"), $Utf8NoBom)
    $r34h = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($r34h.Out -match 'entry-heading. CHANGELOG')) 'scenario 34: an entry with no PR number but with its sections is accepted -- the manual-merge fold'

    # A PRE-FORMAT entry, which is the second legitimate shape: no sections at all, the type carried as a
    # heading field. Every entry this repo folded before August 5, 2026 looks like this, and so does anything
    # folded from a branch that predates the format -- so reporting it would fire on real history.
    $s34ClLegacy = @(
        '# Changelog'
        ''
        'Intro.'
        ''
        "$s34EntryH #99 " + $s34Md + ' An entry from before the format ' + $s34Md + ' Fix ' + $s34Md + ' 2026-08-01'
        ''
        'Body prose, no named sections.'
        ''
        "$s34SubH A properly demoted sub-heading"
        ''
        'More prose.'
        ''
    )
    [System.IO.File]::WriteAllText($s34Cl, (($s34ClLegacy -join "`n") + "`n"), $Utf8NoBom)
    $r34k = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($r34k.Out -match 'entry-heading. CHANGELOG')) 'scenario 34: a pre-format entry declaring its type in the heading is accepted -- no sections required of it'

    # THE PLACEMENT NEITHER RULE CATCHES ALONE, and the reason the check has two: a stray heading directly
    # BELOW the entry heading keeps all three sections in its own block, so the first rule sees a well-formed
    # entry. What gives it away is the entry ABOVE it, now sectionless -- and a current-format heading carries
    # no type field, so the type rule reports that one. The error lands on the real entry rather than on the
    # stray, which is why the message names both possibilities instead of asserting which it found.
    $s34ClAbsorbed = @(
        '# Changelog'
        ''
        'Intro.'
        ''
        "$s34EntryH #123 " + $s34Md + ' A real entry'
        ''
        "$s34EntryH A sub-heading that swallowed the entry"
        ''
    ) + $s34Sections + @('')
    [System.IO.File]::WriteAllText($s34Cl, (($s34ClAbsorbed -join "`n") + "`n"), $Utf8NoBom)
    $r34l = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($r34l.Out -match 'entry-heading. CHANGELOG\.md:5') 'scenario 34: a stray heading directly below an entry heading is caught via the entry it emptied'
    Assert-True ($r34l.Out -match 'declares neither its named sections nor a change type') 'scenario 34: and the message states exactly what is missing'
    Assert-True ($r34l.Out -match 'absorbed by such a heading directly below it') 'scenario 34: naming the second possibility, since the error lands on the victim rather than the cause'

    # An H1 below the intro, and a stray section-level heading, in one document -- so the assert on the
    # second one also proves the scan did not stop at the first. The pre-flat check keyed its boundary on a
    # heading NAME and had to reason carefully about not ending the scan at the very defect it looked for;
    # the boundary is structural now, so the scan simply runs to the end of the file.
    $s34ClMixed = @(
        '# Changelog'
        ''
        'Intro.'
        ''
        "$s34EntryH #123 " + $s34Md + ' A real entry'
        ''
        "$s34SectH What does this change do?"
        ''
        '# A body heading that climbs above every entry'
        ''
        "$s34SectH Tested"
        ''
        "$s34SectH Type of change"
        ''
        'Fix'
        ''
    )
    [System.IO.File]::WriteAllText($s34Cl, (($s34ClMixed -join "`n") + "`n"), $Utf8NoBom)
    $r34i = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($r34i.Out -match 'entry-heading. CHANGELOG\.md:9') 'scenario 34: an H1 below the intro is reported'
    Assert-True ($r34i.Out -match 'climbs above every entry') 'scenario 34: and the message names the consequence in the document'
    Assert-True ($r34i.Out -match 'entry-heading. CHANGELOG\.md:11') 'scenario 34: and the stray section heading AFTER it is still reported -- the scan did not stop'

    # A changelog with no entry at all is the normal state between a release and the next merge: not judged
    # and not an error. Stated as an assert because "reports nothing" and "found nothing to report" look
    # identical from the outside, and the coverage line is what distinguishes them.
    [System.IO.File]::WriteAllText($s34Cl, "# Changelog`n`nNothing merged since the last release.`n", $Utf8NoBom)
    $r34j = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($r34j.Out -match 'entry-heading. CHANGELOG')) 'scenario 34: an entry-less changelog is not an error -- that is the state right after a release'
    Remove-Item -LiteralPath $s34Cl -Force

    # Leaves the fixture with a history-only mention again, which the coverage block below relies on.
    [System.IO.File]::WriteAllText((Join-Path $Fixture 'CONTRIBUTING.md'), (($s24Contributing -join "`n") + "`n"), $Utf8NoBom)

    # --- [COVERAGE]: every category states what it examined, and an empty one says so (issue #221) ---
    # This fixture is the ideal witness and always has been: it carries no agent def, no manual, no
    # persona, no plugin manifest and no lens tree, so those categories are GENUINELY empty. Before
    # #221 the run was therefore green while silently checking nothing in half its categories -- the
    # docstring above even records that as "expected noise, asserted on nowhere below". It is asserted
    # on now: a category that finds nothing must say the number out loud.
    #
    # Deliberately asserts the ZERO cases (the ones that used to be invisible) AND two non-zero cases,
    # because a coverage line that always printed "0" would satisfy the first half while being useless.
    Write-Host "[COVERAGE] every category reports its count, and an empty category is visible" -ForegroundColor Cyan
    $rc = Invoke-Integrity -FixtureRoot $Fixture -Full
    foreach ($cat in @('agent-def', 'manual', 'persona', 'specialist', 'shared', 'written-name')) {
        Assert-True ($rc.Out -match "\[$([regex]::Escape($cat))\] checked 0\b") `
            "coverage: the genuinely empty category '$cat' reports 'checked 0' instead of staying silent"
    }
    Assert-True ($rc.Out -match '\[link-scan/lenses\] checked 0\b') `
        'coverage: the lens category -- the one a teardown removes -- reports 0 on a repo with no lens tree'
    Assert-True ($rc.Out -match '\[link-scan/lenses\] checked 0 -- no repo-lens file') `
        'coverage: the empty lens category also states WHY it is empty, so a reader can tell a teardown from a loss'
    Assert-True ($rc.Out -match '\[link-scan\] checked [1-9]') `
        'coverage: a non-empty category reports its real count -- the line is not hardcoded to 0'
    Assert-True ($rc.Out -match '\[parse\] checked [1-9]') `
        'coverage: parse counts the .ps1 files it actually parsed (the copied script + its libs)'
    # Scenario 24 left the fixture with only a history mention, so this category is legitimately empty
    # here -- and an empty lifecycle scan is exactly the state a reader must not mistake for "the docs
    # are right", so it states its own reason like the lens category does.
    Assert-True ($rc.Out -match '\[lifecycle\] checked 0 -- no printed lifecycle command') `
        'coverage: an empty lifecycle scan says WHY it is empty, so "nothing to enforce" cannot read as "nothing wrong"'
    # Coverage is context, never a finding: it must not move the exit code or manufacture an error.
    # Scenario 16 left the fixture with a real finding, so this run legitimately exits 1 -- what is
    # asserted here is that no coverage line was itself counted as one.
    Assert-True (-not ($rc.Out -match '(?m)^\s*\[COVERAGE\]')) `
        'coverage: the token is the category name, not a literal [COVERAGE] tag -- one line per category, no extra noise'

    # --- check 15: a captured output sample must say what it is bound to ----------------------------
    # The class behind four of test round v11's nine findings. Each case below is one of the two ways
    # this check can fail badly: missing a real unbound sample, or firing on something that is not one.
    # The false-positive half is not optional politeness -- a gate that cries wolf gets an opt-out
    # pasted over every finding and then reports green while asserting nothing.
    # THE PATH HAS TO BE ONE $consumerDocs ACTUALLY NAMES, and this fixture has now been caught by that
    # twice. $consumerDocs holds paths rather than bare names, and both checks Test-Path-skip an entry
    # they cannot find, in silence -- so a fixture writing anywhere else leaves every assertion below
    # passing over a document the check never opened. First it was the move into plugins/; on
    # August 14, 2026 the adoption half split off into plugins/ADOPTION.md and the two plumbing pages
    # went to the repo root (inbound #664), which moved the subject again.
    #
    # ADOPTION.md rather than the root INSTALL.md, deliberately: in the real tree it is the page that
    # carries the captured samples and measured figures these two checks exist for -- the bootstrap's
    # closing line, the 4+15+2 counts. Pointing the fixture at the document that really holds the
    # subject is what keeps this suite honest about what it proves.
    $qsDir = Join-Path $Fixture 'plugins'
    if (-not (Test-Path -LiteralPath $qsDir)) { New-Item -ItemType Directory -Path $qsDir -Force | Out-Null }
    $qs = Join-Path $qsDir 'ADOPTION.md'
    # Fence and box drawing from codepoints, never as literals. The first version wrote the fence
    # literally and silently produced an opening fence with the language on the NEXT line, so the
    # "a command block is not examined" case was testing a language-less block and failing for a
    # reason that had nothing to do with the check. Same discipline as fix-mojibake's ASCII-only
    # source, and for the same class of reason.
    #
    # AND EVERY '$fence + <lang>' BELOW IS PARENTHESISED, which is not style. In PowerShell the comma
    # binds TIGHTER than '+', so @('a', $fence + 'powershell', 'b') parses as ('a', $fence) +
    # ('powershell', 'b') -- four elements, and the language lands on its own line. That is what
    # actually broke the command-block case, twice, while the check under test was correct throughout.
    $bt    = [string][char]0x60
    $fence = $bt + $bt + $bt
    $tree  = 'repo/' + "`n" + [char]0x251C + [char]0x2500 + ' CLAUDE.md'

    # 1. THE FINDING: output quoted with nothing saying what it came from.
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'The closing line reads:', '', $fence,
        'Done: 4 created, 0 already present.', $fence, '', 'Compare it against yours.'
    ) -join "`n", $Utf8NoBom)
    $s1 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($s1.Out -match '\[expected-output\].*ADOPTION\.md') `
        'expected-output: an output sample with no stated binding is reported'
    Assert-True ($s1.Out -match 'expected-output. checked [1-9]') `
        'expected-output: and the coverage line counts samples examined, not check runs'

    # 2. BOUND, three ways -- a version, a date, and a hedge. Each must clear it on its own.
    foreach ($binding in @('Measured on CLI 2.1.220.', 'Measured on 1 August 2026.', 'This varies by repo.')) {
        [System.IO.File]::WriteAllText($qs, @(
            '# Quickstart', '', 'The closing line reads:', '', $fence,
            'Done: 4 created, 0 already present.', $fence, '', $binding
        ) -join "`n", $Utf8NoBom)
        $s2 = Invoke-Integrity -FixtureRoot $Fixture
        Assert-True (-not ($s2.Out -match '\[expected-output\].*ADOPTION\.md')) `
            "expected-output: a sample bound by '$binding' passes"
    }

    # 3. A COMMAND IS NOT A SAMPLE. Tagged blocks are things to run; they cannot go stale under a reader
    #    the way a captured transcript can.
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'Run this:', '', ($fence + 'powershell'),
        'claude plugin install dkj-subagents-alpha@dkj-claude-plugins --scope project', $fence
    ) -join "`n", $Utf8NoBom)
    $s3 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($s3.Out -match '\[expected-output\].*ADOPTION\.md')) `
        'expected-output: a powershell block is a command to run, not examined'

    # 4. A DIAGRAM IS DRAWN, NOT CAPTURED. The check's first real false positive, on the seam diagram in
    #    the root README.
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'The shape is:', '', ($fence + 'text'), $tree, $fence
    ) -join "`n", $Utf8NoBom)
    $s4 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($s4.Out -match '\[expected-output\].*ADOPTION\.md')) `
        'expected-output: a box-drawing diagram is not a captured sample'

    # 5. THE OPT-OUT HAS TO NAME A REASON. A bare marker must not silence the check, or the escape hatch
    #    becomes the way the gate is defeated rather than the way an exception is recorded.
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'Reads:', '', $fence, 'Done: 4 created.', $fence, '', '<!-- unbound-sample: -->'
    ) -join "`n", $Utf8NoBom)
    $s5 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($s5.Out -match '\[expected-output\].*ADOPTION\.md') `
        'expected-output: an opt-out marker with no reason does not silence the check'
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'Reads:', '', $fence, 'Done: 4 created.', $fence, '',
        '<!-- unbound-sample: invented for the test fixture, bound to nothing real -->'
    ) -join "`n", $Utf8NoBom)
    $s6 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($s6.Out -match '\[expected-output\].*ADOPTION\.md')) `
        'expected-output: an opt-out that names a reason does silence it'

    # --- check 16: a measured figure in prose names what it was measured on -------------------------
    # Check 15's class, one step outside its reach: the same staleness, in running prose where there is
    # no fence to mark it. Test round v12's #374 and its unfiled twin one section down. The cases below
    # are again the two ways this fails badly -- missing a real unbound figure, and firing on something
    # that is not one -- plus the three design decisions that could otherwise erode silently: the window
    # is bounded, a fence belongs to check 15, and 'measured' is not a binding.

    # 1. THE FINDING: a byte count with nothing saying whose machine it came from.
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'After the teardown the file is 288 bytes and holds nothing of ours.'
    ) -join "`n", $Utf8NoBom)
    $f1 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($f1.Out -match '\[measured-figure\].*ADOPTION\.md') `
        'measured-figure: a byte count in prose with no stated binding is reported'
    Assert-True ($f1.Out -match 'measured-figure. checked [1-9]') `
        'measured-figure: and the coverage line counts figures examined, not check runs'

    # 2. BOUND, five ways -- a date, a test round, a version, a named profile state, and a hedge. Each
    #    must clear it on its own, because a writer will reach for whichever one fits the sentence.
    foreach ($binding in @(
        'Measured on 1 August 2026.', 'Measured in round v12.', 'Measured on CLI 2.1.220.',
        'Measured on a virgin profile.', 'The figure varies by platform.'
    )) {
        [System.IO.File]::WriteAllText($qs, @(
            '# Quickstart', '', "After the teardown the file is 288 bytes. $binding"
        ) -join "`n", $Utf8NoBom)
        $f2 = Invoke-Integrity -FixtureRoot $Fixture
        Assert-True (-not ($f2.Out -match '\[measured-figure\].*ADOPTION\.md')) `
            "measured-figure: a figure bound by '$binding' passes"
    }

    # 3. THE WINDOW REACHES THE NEIGHBOURING BLOCKS, IN BOTH DIRECTIONS. A table row is bound by the
    #    paragraph introducing the table (the #339 table) or by the note underneath it saying which
    #    column came from where (the bracket table). Neither binding sits on the row itself, and a
    #    line-count window would have to guess how many rows the table has.
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'Measured on a virgin profile, 1 August 2026:', '',
        '| file | size |', '|---|---|', '| settings.json | 288 bytes |'
    ) -join "`n", $Utf8NoBom)
    $f3 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($f3.Out -match '\[measured-figure\].*ADOPTION\.md')) `
        'measured-figure: a binding in the paragraph ABOVE a table binds its rows'
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'The sizes:', '',
        '| file | size |', '|---|---|', '| settings.json | 288 bytes |', '',
        'The right-hand column is round v12.'
    ) -join "`n", $Utf8NoBom)
    $f4 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($f4.Out -match '\[measured-figure\].*ADOPTION\.md')) `
        'measured-figure: a binding in the paragraph BELOW a table binds its rows too'

    # 4. AND IT STOPS THERE. A binding two blocks away does NOT count -- otherwise the gate is satisfied
    #    by a date in an unrelated subsection, which is how a window quietly becomes section-wide.
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'Measured on a virgin profile, 1 August 2026.', '',
        'An unrelated paragraph sits in between.', '', 'The file is 288 bytes.'
    ) -join "`n", $Utf8NoBom)
    $f5 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($f5.Out -match '\[measured-figure\].*ADOPTION\.md') `
        'measured-figure: a binding two blocks away is out of reach -- the window is bounded'

    # 5. A FENCED FIGURE BELONGS TO CHECK 15. Counting it here would report one sample as two findings,
    #    and would flag verbatim command output that is deliberately reproduced.
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'Measured in round v12, the output reads:', '', ($fence + 'text'),
        'known_marketplaces.json  288 bytes', $fence
    ) -join "`n", $Utf8NoBom)
    $f6 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($f6.Out -match '\[measured-figure\] checked 0') `
        'measured-figure: a figure inside a fence is check 15''s, and is not counted twice'

    # 6. 'measured' ON ITS OWN IS NOT A BINDING. It says the author saw the number, which was true of
    #    every finding this check exists for. Same rejection as check 15 makes, and for the same reason.
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'The clone is deleted (measured: 288 bytes, gone).'
    ) -join "`n", $Utf8NoBom)
    $f7 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($f7.Out -match '\[measured-figure\].*ADOPTION\.md') `
        'measured-figure: the word ''measured'' alone does not bind a figure'

    # 7. NOT EVERY 'byte' IS A FIGURE. 'byte-identical' is a word, and a check that flagged it would be
    #    training writers to paste opt-outs over prose. The leading digit is what makes it a measurement.
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'The install leaves the file byte-identical, so the diff is empty.'
    ) -join "`n", $Utf8NoBom)
    $f8 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($f8.Out -match '\[measured-figure\] checked 0') `
        'measured-figure: ''byte-identical'' carries no number and is not a figure'

    # 8. THE OPT-OUT HAS TO NAME A REASON, exactly as check 15's does.
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'The file is 288 bytes.', '', '<!-- unbound-figure: -->'
    ) -join "`n", $Utf8NoBom)
    $f9 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True ($f9.Out -match '\[measured-figure\].*ADOPTION\.md') `
        'measured-figure: an opt-out marker with no reason does not silence the check'
    [System.IO.File]::WriteAllText($qs, @(
        '# Quickstart', '', 'The file is 288 bytes.', '',
        '<!-- unbound-figure: invented for the test fixture, bound to nothing real -->'
    ) -join "`n", $Utf8NoBom)
    $f10 = Invoke-Integrity -FixtureRoot $Fixture
    Assert-True (-not ($f10.Out -match '\[measured-figure\].*ADOPTION\.md')) `
        'measured-figure: an opt-out that names a reason does silence it'

    # RETIRED, AUGUST 8, 2026 -- check 17's scenarios 33-37, with the check itself. They held the four
    # per-plugin CHANGELOG intros against Build-PluginChangelogIntro, which was the right repair for a
    # real defect: the intro was write-once, so all four kept naming a retired marketplace. The files
    # are gone -- a consumer already receives the root CHANGELOG.md through the marketplace clone -- so
    # there is no second copy left to hold against a generator.
} finally {
    if (Test-Path -LiteralPath $Fixture) { Remove-Item -Recurse -Force -LiteralPath $Fixture -ErrorAction SilentlyContinue }
}

Complete-IntegritySuite
