<#
.SYNOPSIS
    check-plugin-integrity.ps1, check 13b and [COVERAGE]: no branch document is left behind between
    branches, and every category states what it examined.

.DESCRIPTION
    The fixture, the assert helpers and Invoke-Integrity live in check-plugin-integrity-fixture.ps1,
    which also records why this suite family is more than one file. Split out of -entries under #2304
    (step 4).

    EVERY SCENARIO HERE PASSES -Full, and that is load-bearing: the six branch-template scenarios and the
    [COVERAGE] scenario assert about checks the fixture skips for speed. An ABSENCE assert under a skip
    would pass vacuously, which is why the skip list is documented beside Invoke-Integrity rather than here.

    Pure ASCII (repo convention for .ps1).
#>
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'check-plugin-integrity-fixture.ps1')

$Fixture = Join-Path ([System.IO.Path]::GetTempPath()) ("check-plugin-integrity-branch-document-$PID-$([guid]::NewGuid().ToString('n'))")

try {
    New-IntegrityFixture -Fixture $Fixture

    # --- check 13b: no branch document is left behind between branches ----------------------------
    # WHAT THIS PINS HAS BEEN INVERTED, AND THE ARGUMENT BEHIND IT DID NOT SURVIVE INTACT (August 23, 2026).
    # It held two generated templates under branch/templates/ to Get-BranchTemplates, then the merged
    # document's RESET state to the formatter, both on the same reasoning: a document generated by a
    # formatter must not become a second definition of the format. That reasoning needed a generated
    # document to hold, and there is none -- the document exists for the lifetime of a branch, so the trunk
    # carries no copy and a hand-edit to a reset state is not a thing that can happen.
    #
    # SO THE SUBJECT IS THE INVARIANT THAT REPLACED IT: no document anywhere declares the trunk. Absent is
    # the trunk's normal state, a document naming this branch is work in progress, and one naming the trunk
    # is a leftover from a fold that ran under the older behaviour. Asserted in every direction, because a
    # check that only ever passes is indistinguishable from one that reads nothing.
    Write-Host 'check 13b -- no branch document is left behind between branches' -ForegroundColor Cyan
    $bdRel  = (Get-BranchFilePaths).File -replace '/', '\'
    $bdPath = Join-Path $Fixture $bdRel
    New-Item -ItemType Directory -Path (Split-Path -Parent $bdPath) -Force | Out-Null
    if (Test-Path -LiteralPath $bdPath) { Remove-Item -LiteralPath $bdPath -Force }

    $r13bAbsent = Invoke-Integrity -FixtureRoot $Fixture -Full
    Assert-True (-not ($r13bAbsent.Out -match '\[branch-template\].*names the trunk')) 'check 13b: an absent document is the trunk in its normal state, and is silent'
    Assert-True ($r13bAbsent.Out -match '\[branch-template\] checked 1') 'check 13b: and it was actually examined -- the pass is not an empty scan'
    Assert-True ($r13bAbsent.Out -match 'absent, which is the trunk between branches') 'check 13b: the coverage line says WHICH state it found, so a pass cannot read as a skip'

    # A DOCUMENT HOLDING A BRANCH'S WORK IS FINE, which is the ordinary state on any branch -- including the
    # branch this check is running on.
    [System.IO.File]::WriteAllText($bdPath, (((Format-Development -Branch 'feat/somebodys-work-v1' -Id '20260823-090000') -join "`n") + "`n"), $Utf8NoBom)
    $r13bOnBranch = Invoke-Integrity -FixtureRoot $Fixture -Full
    Assert-True (-not ($r13bOnBranch.Out -match '\[branch-template\].*names the trunk')) 'check 13b: a document holding a branch''s work is not a finding'
    Assert-True ($r13bOnBranch.Out -match "declaring 'feat/somebodys-work-v1'") 'check 13b: and the coverage line names whose work it is'

    # THE LEFTOVER. This is the exact file the old behaviour wrote on every fold, so this case is what the
    # inversion is FOR: what used to be the asserted-correct state is now the one error.
    [System.IO.File]::WriteAllText($bdPath, (((Format-Development -Branch '') -join "`n") + "`n"), $Utf8NoBom)
    $r13bLeftover = Invoke-Integrity -FixtureRoot $Fixture -Full
    Assert-Equal 1 $r13bLeftover.Code 'check 13b: a document declaring the trunk is an error'
    Assert-True ($r13bLeftover.Out -match 'names the trunk') 'check 13b: and the message says what is wrong with it'
    Assert-True ($r13bLeftover.Out -match 'Delete it') 'check 13b: and what to do about it, since the repair is one command'

    # A DOCUMENT BELONGING TO NOBODY. Every reader of this file -- the fold, the two local gates, the CI gate
    # -- identifies a branch's work by the name in the heading, so one without a name is unreadable to all of
    # them. Reported rather than passed, because silence here is what a hand-created file would buy.
    [System.IO.File]::WriteAllText($bdPath, "# Development`n`nNo branch named anywhere.`n", $Utf8NoBom)
    $r13bNameless = Invoke-Integrity -FixtureRoot $Fixture -Full
    Assert-Equal 1 $r13bNameless.Code 'check 13b: a document declaring no branch at all is an error'
    Assert-True ($r13bNameless.Out -match 'declares no branch in its heading') 'check 13b: and it is reported as its own case, not as a trunk leftover'

    # THE CHECK READS THE FIXTURE'S OWN repo-config, and it still has to now that it generates no content.
    # Get-BranchTrunkName is a seam: a repo whose trunk is 'master' has a DIFFERENT set of documents that
    # count as leftovers, and answering it from this repo's default would pass exactly the file that repo
    # needs caught. Asserted in both directions on one fixture, because silence alone is also what a check
    # that stopped reading would produce.
    $fixCfgDir = Join-Path $Fixture 'scripts'
    New-Item -ItemType Directory -Path $fixCfgDir -Force | Out-Null
    $fixCfg = Join-Path $fixCfgDir 'repo-config.ps1'
    [System.IO.File]::WriteAllText($fixCfg, "function Get-TrunkBranchName { 'master' }`n", $Utf8NoBom)
    $masterReset = & {
        . $fixCfg
        . (Join-Path $PSScriptRoot '..\lib\entry-scaffold-lib.ps1')
        ((Format-Development -Branch '') -join "`n") + "`n"
    }
    [System.IO.File]::WriteAllText($bdPath, $masterReset, $Utf8NoBom)
    $r13bMaster = Invoke-Integrity -FixtureRoot $Fixture -Full
    Assert-Equal 1 $r13bMaster.Code 'check 13b: a leftover naming the FIXTURE''s trunk is caught, not this repo''s'
    Assert-True ($r13bMaster.Out -match "names the trunk \('master'\)") 'check 13b: and the message quotes the trunk that fixture actually declared'

    # The mirror image on the same fixture: 'main' is an ordinary branch name in a repo whose trunk is
    # 'master', so the very shape that was an error two asserts ago must now be silent.
    [System.IO.File]::WriteAllText($bdPath, (((Format-Development -Branch 'main' -Id '20260823-090000') -join "`n") + "`n"), $Utf8NoBom)
    $r13bMainOnMaster = Invoke-Integrity -FixtureRoot $Fixture -Full
    Assert-True (-not ($r13bMainOnMaster.Out -match '\[branch-template\].*names the trunk')) `
        'check 13b: and where the trunk is master, a document naming main is just a branch'
    # Back to the absent state with no config, so nothing after this inherits the fixture's answer.
    Remove-Item -LiteralPath $fixCfg -Force
    Remove-Item -LiteralPath $bdPath -Force

    # The quiet CONTRIBUTING.md the [COVERAGE] block below needs: a root document that prints no lifecycle
    # command. See $s24Contributing in the fixture for why it is shared state stated once.
    [System.IO.File]::WriteAllText((Join-Path $Fixture 'CONTRIBUTING.md'), (($s24Contributing -join "`n") + "`n"), $Utf8NoBom)

    # --- [COVERAGE]: every category states what it examined, and an empty one says so (issue #221) ---
    # This fixture is the ideal witness and always has been: it carries no agent def, no manual, no
    # persona, no plugin manifest and no lens tree, so those categories are GENUINELY empty. Before
    # #221 the run was therefore green while silently checking nothing in half its categories -- the
    # docstring above even records that as "expected noise, asserted on nowhere below". It is asserted
    # on now: a category that finds nothing must say the number out loud.
    #
    # Deliberately asserts the ZERO cases (the ones that used to be invisible) AND two non-zero cases,
    # because a coverage line that always printed "0" would satisfy the first half while being useless.
    Write-Host "[COVERAGE] every category reports its count, and an empty category is visible" -ForegroundColor Cyan
    $rc = Invoke-Integrity -FixtureRoot $Fixture -Full
    foreach ($cat in @('agent-def', 'manual', 'persona', 'specialist', 'shared', 'written-name')) {
        Assert-True ($rc.Out -match "\[$([regex]::Escape($cat))\] checked 0\b") `
            "coverage: the genuinely empty category '$cat' reports 'checked 0' instead of staying silent"
    }
    Assert-True ($rc.Out -match '\[link-scan/lenses\] checked 0\b') `
        'coverage: the lens category -- the one a teardown removes -- reports 0 on a repo with no lens tree'
    Assert-True ($rc.Out -match '\[link-scan/lenses\] checked 0 -- no repo-lens file') `
        'coverage: the empty lens category also states WHY it is empty, so a reader can tell a teardown from a loss'
    Assert-True ($rc.Out -match '\[link-scan\] checked [1-9]') `
        'coverage: a non-empty category reports its real count -- the line is not hardcoded to 0'
    Assert-True ($rc.Out -match '\[parse\] checked [1-9]') `
        'coverage: parse counts the .ps1 files it actually parsed (the copied script + its libs)'
    # The CONTRIBUTING.md written above carries no lifecycle command, so this category is legitimately
    # empty here -- and an empty lifecycle scan is exactly the state a reader must not mistake for "the docs
    # are right", so it states its own reason like the lens category does.
    Assert-True ($rc.Out -match '\[lifecycle\] checked 0 -- no printed lifecycle command') `
        'coverage: an empty lifecycle scan says WHY it is empty, so "nothing to enforce" cannot read as "nothing wrong"'
    # Coverage is context, never a finding: it must not move the exit code or manufacture an error.
    # The exit code is deliberately not asserted: it depends on whatever findings the fixture carries,
    # which is a property of the fixture and not of coverage. What is asserted here is that no coverage
    # line was itself counted as one.
    Assert-True (-not ($rc.Out -match '(?m)^\s*\[COVERAGE\]')) `
        'coverage: the token is the category name, not a literal [COVERAGE] tag -- one line per category, no extra noise'
} finally {
    if (Test-Path -LiteralPath $Fixture) { Remove-Item -Recurse -Force -LiteralPath $Fixture -ErrorAction SilentlyContinue }
}

Complete-IntegritySuite
